version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Paris"
    commit-message:
       prefix: "chore(deps/actions)"
