version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Paris"
    commit-message:
       prefix: "chore(deps)"
    open-pull-requests-limit: 10
    groups:
      fastify:
        patterns:
          - "fastify"
          - "@fastify/*"
        update-types:
          - "major"
          - "minor"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
        update-types:
          - "major"
          - "minor"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
        update-types:
          - "major"
          - "minor"
      i18next:
        patterns:
          - "i18next"
          - "i18next-*"
          - "*-i18next"
        update-types:
          - "major"
          - "minor"
      react-query:
        patterns:
          - "@tanstack/react-query"
          - "@tanstack/react-query-devtools"
      sentry:
        patterns:
          - "@sentry/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Paris"
    commit-message:
       prefix: "chore(deps/actions)"
