nodeLinker: node-modules

npmScopes:
  ou-ca:
    npmAuthToken: "${NPM_GITHUB_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
