name: Validate PR

on:
  pull_request:

# concurrency:
#   group: ${{ github.ref }}
#   cancel-in-progress: true

jobs:
  validate-pr:
#     environment:
#       name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'production' || 'preview' }}

    runs-on: docker

#     permissions:
#       pull-requests: write
#       contents: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: ./.forgejo/actions/validate

      # We had cases where the PR typecheck was fine, but the build failed
      # Let's make sure we don't deploy something that doesn't build
      - uses: ./.forgejo/actions/build-frontend
        with:
          with-sentry: false
          sentry-url: ${{ vars.SENTRY_URL }}
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-org: ${{ vars.SENTRY_ORG }}
          sentry-project: ${{ vars.SENTRY_PROJECT }}

      - uses: ./.forgejo/actions/auto-approve-pr
        if: ${{ github.actor == 'renovate' }}
        continue-on-error: true
        with:
          tea-token: ${{ secrets.FORGEJO_TOKEN }}

  deploy-cloudflare:
    needs: validate-pr

#     environment:
#       name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'production' || 'preview' }}
#       url: ${{ steps.deploy.outputs.deployment-url }}

#     permissions:
#       deployments: write

    runs-on: docker

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: ./.forgejo/actions/deploy-cloudflare-pages
        id: deploy
        with:
          artifact-name: dist-frontend
          artifact-path: dist
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
