name: "auto approve"
description: "Auto approve PR"

inputs:
  tea-token:
    description: "Token for tea client to approve PRs"
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: download tea client
      run: |
        wget -O /usr/local/bin/tea https://dl.gitea.io/tea/0.9.2/tea-0.9.2-linux-amd64
        chmod +x /usr/local/bin/tea
      shell: bash

    - name: login to forgejo
      run: tea login add -n user
      shell: bash
      env:
        GITEA_SERVER_URL: http://forgejo-http.default.svc.cluster.local:3000
        GITEA_SERVER_TOKEN: ${{ inputs.tea-token }}

    # https://gist.github.com/xt0rted/46475099dc0a70ba63e16e3177407872
    # https://github.com/dependabot/fetch-metadata/issues/111
    # - name: Generate app token
    #   id: generate-app-token
    #   uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
    #   with:
    #     app_id: ${{ inputs.bot-app-id }}
    #     private_key: ${{ inputs.bot-private-key }}


    # - name: Authenticate gh cli with app token
    #   shell: bash
    #   run: echo "${{ steps.generate-app-token.outputs.token }}" | gh auth login --with-token

    # # From https://github.com/dependabot/fetch-metadata
    # - name: Approve a PR if not already approved
    #   shell: bash
    #   id: dependabot-approve
    #   run: |
    #     gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
    #     if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
    #     then gh pr review --approve "$PR_URL"
    #     else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
    #     fi
    #   env:
    #     PR_URL: ${{ github.event.pull_request.html_url }}
