name: "auto approve"
description: "Auto approve PR"

inputs:
  tea-token:
    description: "Token for tea client to approve PRs"
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: download tea client
      run: |
        wget -O /usr/local/bin/tea https://dl.gitea.io/tea/0.9.2/tea-0.9.2-linux-amd64
        chmod +x /usr/local/bin/tea
      shell: bash

    - name: login to forgejo
      run: tea login add -n user
      shell: bash
      env:
        GITEA_SERVER_URL: http://forgejo-http.default.svc.cluster.local:3000
        GITEA_SERVER_TOKEN: ${{ inputs.tea-token }}

    - run: tea pr approve ${{ github.event.pull_request.number }}
      shell: bash
