name: "auto approve"
description: "Auto approve PR"

inputs:
  tea-token:
    description: "Token for tea client to approve PRs"
    required: true
  tea-version:
    description: "Version of tea client to use"
    required: false
    default: "0.9.2"

runs:
  using: "composite"

  steps:
    - name: Cache tea binary
      id: cache-tea
      uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
      with:
        path: /usr/local/bin/tea
        key: tea-${{ inputs.tea-version }}-linux-amd64

    - name: download tea client
      if: steps.cache-tea.outputs.cache-hit != 'true'
      run: |
        wget -O /usr/local/bin/tea https://dl.gitea.io/tea/${{ inputs.tea-version }}/tea-${{ inputs.tea-version }}-linux-amd64
        chmod +x /usr/local/bin/tea
      shell: bash

    - name: login to forgejo
      run: tea login add -n user
      shell: bash
      env:
        GITEA_SERVER_URL: http://forgejo-http.default.svc.cluster.local:3000
        GITEA_SERVER_TOKEN: ${{ inputs.tea-token }}

    - run: tea pr approve ${{ github.event.pull_request.number }}
      shell: bash
