name: "node & pnpm install"
description: "Install Node.js and pnpm dependencies"

runs:
  using: "composite"

  steps:
    - uses: https://github.com/pnpm/action-setup@v4

    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version-file: .tool-versions
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install
