name: "node & pnpm install"
description: "Install Node.js and pnpm dependencies"

runs:
  using: "composite"

  steps:
    - uses: https://github.com/pnpm/action-setup@v4

    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        node-version-file: .tool-versions
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install
