name: "node & pnpm install"

runs:
  using: "composite"

  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version-file: .tool-versions
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install
