name: "deploy to Cloudflare Pages"
description: "Deploy frontend to Cloudflare Pages"

inputs:
  artifact-name:
    description: "Artifact name"
    required: true
  artifact-path:
    description: "Artifact path"
    default: "dist"
    required: false
  cloudflare-api-token:
    description: "Cloudflare API token"
    required: true
  cloudflare-account-id:
    description: "Cloudflare account ID"
    required: true
  cloudflare-project-name:
    description: "Cloudflare project name"
    required: true

outputs:
  deployment-url:
    description: "Deployment URL"
    value: ${{ steps.deploy.outputs.deployment-url }}

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version-file: .tool-versions
        cache: "pnpm"

    - uses: https://code.forgejo.org/forgejo/download-artifact@d8d0a99033603453ad2255e58720b460a0555e1e # v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    # https://github.com/cloudflare/wrangler-action/issues/181
    - run: echo "ignore-workspace-root-check=true" >> .npmrc
      shell: bash

    - uses: https://github.com/cloudflare/wrangler-action@6d58852c35a27e6034745c5d0bc373d739014f7f # v3
      with:
        apiToken: ${{ inputs.cloudflare-api-token }}
        accountId: ${{ inputs.cloudflare-account-id }}
        command: pages deploy ${{ inputs.artifact-path }} --project-name=${{ inputs.cloudflare-project-name }} --commit-dirty=true --commit-hash=${{ github.sha }}
