name: "deploy to Cloudflare Pages"
description: "Deploy frontend to Cloudflare Pages"

inputs:
  artifact-name:
    description: "Artifact name"
    required: true
  artifact-path:
    description: "Artifact path"
    default: "dist"
    required: false
  cloudflare-api-token:
    description: "Cloudflare API token"
    required: true
  cloudflare-account-id:
    description: "Cloudflare account ID"
    required: true
  cloudflare-project-name:
    description: "Cloudflare project name"
    required: true

outputs:
  deployment-url:
    description: "Deployment URL"
    value: ${{ steps.deploy.outputs.deployment-url }}

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version-file: .tool-versions
        cache: "pnpm"

    - uses: https://code.forgejo.org/forgejo/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    # https://github.com/cloudflare/wrangler-action/issues/181
    - run: echo "ignore-workspace-root-check=true" >> .npmrc
      shell: bash

    - uses: https://github.com/cloudflare/wrangler-action@f84a562284fc78278ff9052435d9526f9c718361 # v3
      with:
        apiToken: ${{ inputs.cloudflare-api-token }}
        accountId: ${{ inputs.cloudflare-account-id }}
        command: pages deploy ${{ inputs.artifact-path }} --project-name=${{ inputs.cloudflare-project-name }} --commit-dirty=true --commit-hash=${{ github.sha }}
