import type { BreederCode } from "../behavior/breeder.js";

export type SearchCriteria = {
  entryId?: string;
  inventoryId?: string;
  observerIds?: string[];
  temperature?: number | null;
  weatherIds?: string[];
  associateIds?: string[];
  time?: string;
  duration?: string;
  classIds?: string[];
  speciesIds?: string[];
  departmentIds?: string[];
  townIds?: string[];
  localityIds?: string[];
  number?: number;
  numberEstimateIds?: string[];
  sexIds?: string[];
  ageIds?: string[];
  distance?: number | null;
  distanceEstimateIds?: string[];
  fromDate?: string | null;
  toDate?: string | null;
  comment?: string;
  breeders?: BreederCode[];
  behaviorIds?: string[];
  environmentIds?: string[];
  ownerId?: string;
};
