name: "auto approve"
description: "Auto approve PR"

inputs:
  bot-app-id:
    description: "GitHub App ID"
    required: true
  bot-private-key:
    description: "GitHub App private key"
    required: true

runs:
  using: "composite"

  steps:
    # https://gist.github.com/xt0rted/46475099dc0a70ba63e16e3177407872
    # https://github.com/dependabot/fetch-metadata/issues/111
    - name: Generate app token
      id: generate-app-token
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
      with:
        app_id: ${{ inputs.bot-app-id }}
        private_key: ${{ inputs.bot-private-key }}


    - name: Authenticate gh cli with app token
      shell: bash
      run: echo "${{ steps.generate-app-token.outputs.token }}" | gh auth login --with-token

    # From https://github.com/dependabot/fetch-metadata
    - name: Approve a PR if not already approved
      shell: bash
      id: dependabot-approve
      run: |
        gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
        if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
        then gh pr review --approve "$PR_URL"
        else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
        fi
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
