name: Build Frontend

on:
  workflow_call:
    inputs:
      with-sentry:
        required: false
        type: boolean

jobs:
  build-frontend:
    environment:
      name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'production' || 'preview' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: ./.github/actions/install

      - uses: ./.github/actions/build
        with:
          with-sentry: ${{ inputs.with-sentry }}
          sentry-url: ${{ vars.SENTRY_URL }}
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-org: ${{ vars.SENTRY_ORG }}
          sentry-project: ${{ vars.SENTRY_PROJECT }}
