name: Build Frontend

on:
  workflow_call:
    inputs:
      with-sentry:
        required: false
        type: boolean

jobs:
  build-frontend:
    environment: 
      name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'production' || 'preview' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm frontend build
        env:
          APP_VERSION: ${{ github.sha }}
          ENABLE_SENTRY: ${{ inputs.with-sentry }}
          SENTRY_URL: ${{ vars.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}

      - uses: actions/upload-artifact@v4
        with:
          name: dist-frontend
          path: packages/frontend/dist/
          if-no-files-found: error
