name: Deploy to Cloudflare Pages

on:
  workflow_call:

jobs:
  deploy-cloudflare-pages:
    permissions:
      deployments: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: dist-frontend
          path: dist
      
      - run: pwd
      - run: ls -R dist

      # - uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     command: pages deploy dist --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }}
