name: Deploy to Cloudflare Pages

on:
  workflow_call:

jobs:
  deploy-cloudflare-pages:
    environment:
      name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}

    permissions:
      deployments: write

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/deploy-cloudflare-pages
        with:
          artifact-name: dist-frontend
          artifact-path: dist
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
