name: Deploy to Cloudflare

on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
      branch:
        required: true
        type: string
      distPath:
        required: true
        type: string

jobs:
  deploy-cloudflare:
    runs-on: ubuntu-latest

    steps:

      - name: Retrieve artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}

      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          branch: ${{ inputs.branch }}
          directory: ${{ inputs.distPath }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
