name: Validate, Test & Build

on:
  workflow_call:

jobs:
  validate-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: .tool-versions
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Biome
        run: pnpm --aggregate-output --recursive run biome:ci

      - name: Test
        run: pnpm --aggregate-output --recursive run test

      - name: Typecheck
        run: pnpm --aggregate-output --recursive run typecheck
