name: Validate, Test & Build

on:
  workflow_call:

jobs:
  validate-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup versions
        run: |
          echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Biome
        run: pnpm --aggregate-output --recursive run biome:ci

      - name: Test
        run: pnpm --aggregate-output --recursive run test
        
      - name: Lint
        run: pnpm --aggregate-output --recursive run lint:ci

      - name: Typecheck
        run: pnpm --aggregate-output --recursive run typecheck
