name: Validate, Test & Build

on:
  workflow_call:

jobs:
  validate-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: ./.github/actions/install

      - name: Biome
        run: pnpm --aggregate-output --recursive run biome:ci

      - name: Test
        run: pnpm --aggregate-output --recursive run test

      - name: Typecheck
        run: pnpm --aggregate-output --recursive run typecheck
