name: Build, Test & Deploy

on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/_validate.yml
    secrets: inherit

  build-frontend:
    uses: ./.github/workflows/_build-frontend.yml
    secrets: inherit
    with:
      with-sentry: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

  deploy-cloudflare:
    needs: [validate, build-frontend]
    uses: ./.github/workflows/_deploy-cloudflare-pages.yml
    secrets: inherit

  publish-backend-image:
    runs-on: ubuntu-latest

    outputs:
      image-label: ${{ steps.meta.outputs.version }}
      image-digest: ${{ steps.docker_build.outputs.digest }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        id: setup-node
        with:
          node-version-file: .tool-versions

      - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}-backend
          tags: |
            type=ref,event=branch
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=false

      - uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3

      - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3
        id: buildx

      - uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Rewrite Node version for Docker
        id: rewrite-node-version
        run: |
          echo "NODE_IMAGE_VERSION=$(echo '${{ steps.setup-node.outputs.node-version }}' | cut -c2- )" >> $GITHUB_ENV

      - name: Build and push to GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            "NODE_IMAGE_VERSION=${{ env.NODE_IMAGE_VERSION }}"
            "GIT_SHA=${{ github.sha }}"
          context: .
          platforms: |
            linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-backend-trigger:
    environment: 
      name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'production' || 'preview' }}
  
    needs: [validate, publish-backend-image]
    concurrency: deploy-backend-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
      - name: Dispatch backend image update
        run: gh workflow run --repo alexandresoro/k3s -f label=${{ needs.publish-backend-image.outputs.image-label }} -f digest=${{ needs.publish-backend-image.outputs.image-digest }} -f isProduction=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }} ouca-backend-image-update.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
