name: Check build

on:
  push:
    branches:
      - master
      - dev
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master

jobs:
  check-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - node-version: 16.x
            type: "build,lts"
          # - node-version: 17.x
          #   type: "next"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test -- --passWithNoTests

      - name: Build
        run: npm run build

  publish-docker:
    needs: check-build

    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set the default docker tag
        run: |
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Set docker tag as dev if on dev branch
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "DOCKER_TAG=dev" >> $GITHUB_ENV

      - name: Retrieve docker label if this is a tag push
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
