name: Deploy on Netlify

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-netlify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test -- --passWithNoTests
        
      - name: Build
        run: GENERATE_SOURCEMAP=false npm run build
