name: Deploy on Netlify

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-netlify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test -- --passWithNoTests
        
      - name: Build
        run: GENERATE_SOURCEMAP=false REACT_APP_API_URL=${{secrets.REACT_APP_API_URL}} npm run build

      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
