name: PNPM dependencies maintenance

on:
  schedule:
    - cron: '0 5 * * MON'
  workflow_dispatch:

jobs:
  pnpm-dedupe:
    runs-on: ubuntu-latest

    steps:
      # https://gist.github.com/xt0rted/46475099dc0a70ba63e16e3177407872
      # https://github.com/dependabot/fetch-metadata/issues/111
      - name: Generate app token
        id: generate-app-token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-app-token.outputs.token }}

      - name: Setup versions
        run: |
          echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> $GITHUB_ENV
          echo "PNPM_VERSION=$(jq -r .engines.pnpm package.json | sed -En 's/^(~|\^|>=)*([0-9]+\.[0-9]+\.[0-9]+$)/\2/p')" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Run dedupe
        run: pnpm dedupe

      - name: Check if there's anything to commit
        id: git-diff
        run: |
          echo "has-changes=$(git diff --exit-code)" >> $GITHUB_OUTPUT
        outputs:
          has-changes: ${{ steps.git-diff.outputs.has-changes }}

      - uses: EndBug/add-and-commit@v9
        if: steps.git-diff.outputs.has-changes == 'true'
        with:
          add: "pnpm-lock.yaml"
          message: "chore(deps): dedupe pnpm dependencies"
          new_branch: "deps/pnpm-dedupe"
