name: Publish Snapshot

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  check-build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm run test -- --passWithNoTests

      - name: Build
        run: GENERATE_SOURCEMAP=false REACT_APP_API_URL="" npm run build
        
      - name: Compute the release name
        run: |
          echo "release_tag=v`date '+%Y-%m-%d_%H-%M-%S'`" >> $GITHUB_ENV
          
      - name: Compute the release name for tags
        if: startsWith(github.ref, 'refs/tags/')      
        run: |
          echo "release_tag=v${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Prepare release content
        run: |
          tar -cvzf ouca-web-${env.release_tag}.tar.gz -C build/ .
          
      - name: Publish the release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            ouca-web-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
