name: Validate PR

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr:
    environment:
      name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'production' || 'preview' }}

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: ./.github/actions/validate

      # We had cases where the PR typecheck was fine, but the build failed
      # Let's make sure we don't deploy something that doesn't build
      - uses: ./.github/actions/build-frontend
        with:
          with-sentry: false
          sentry-url: ${{ vars.SENTRY_URL }}
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-org: ${{ vars.SENTRY_ORG }}
          sentry-project: ${{ vars.SENTRY_PROJECT }}

      - uses: ./.github/actions/auto-approve-pr
        if: ${{ github.actor == 'renovate[bot]' }}
        continue-on-error: true
        with:
          bot-app-id: ${{ secrets.BOT_APP_ID }}
          bot-private-key: ${{ secrets.BOT_PRIVATE_KEY }}

  deploy-cloudflare:
    needs: validate-pr

    environment:
      name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}

    permissions:
      deployments: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: ./.github/actions/deploy-cloudflare-pages
        id: deploy
        with:
          artifact-name: dist-frontend
          artifact-path: dist
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
