name: Validate PR

on:
  pull_request:

jobs:
  validate-pr:    
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      with-sentry: false
      deploy-frontend: true
      upload-backend: false
