name: Validate PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      nodeVersion: ${{ steps.nodeVersion.outputs.nodeVersion }}

    steps:
      - name: Setup Node version
        id: nodeVersion
        run: |
          echo "nodeVersion=18" >> $GITHUB_OUTPUT
          echo "nodeVersion=18" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          files_yaml: |
            src:
              - '**/*.ts'
              - '**/*.tsx'
              - '**/*.js'
            eslint:
              - '**/.eslintrc.*'
              - packages/eslint-config/**

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: List all changed eslint files
        run: |
          for file in ${{ steps.changed-files.outputs.eslint_all_changed_files }}; do
            echo "$file was changed"
          done

      - name: List all changed src files
        run: |
          for file in ${{ steps.changed-files.outputs.src_all_changed_files }}; do
            echo "$file was changed"
          done

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeVersion }}
          cache: "pnpm"

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install dependencies
        run: pnpm install

      - run: pnpm run backend generate-graphql

      - name: Rome
        run: pnpm run rome:ci

      - name: Test
        run: pnpm --aggregate-output --recursive run test
        
      - name: Lint - complete
        # Do a complete lint only whenever linter config has changed
        if: steps.changed-files.outputs.eslint_any_changed == 'true'
        run: pnpm --aggregate-output --recursive run lint

      - name: Lint only changed files
        # Lint only changed files when no linter config has changed
        if: steps.changed-files.outputs.eslint_any_changed != 'true'
        run: pnpm eslint ${{ steps.changed-files.outputs.src_all_changed_files }}

      - name: Lint
        run: pnpm --aggregate-output --recursive run lint

      - name: Build
        run: pnpm run build:ci
        env:
          # Only enable Sentry on new commits in default branch
          ENABLE_SENTRY: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          SENTRY_RELEASE: ${{ github.sha }}
          SENTRY_URL: ${{ vars.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
      
      - name: Deploy to CloudFlare - frontend
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: "./packages/frontend/dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
