name: Validate PR

on:
  pull_request:

jobs:
  validate-pr:    
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    with:
      with-sentry: false
      deploy-frontend: true
      upload-backend: false

  deploy-frontend:
    needs: validate-pr
    concurrency:
      group: deploy-frontend-${{ github.ref }}
      cancel-in-progress: true

    uses: ./.github/workflows/_deploy-cloudflare.yml
    secrets: inherit
    with:
      artifact: dist-frontend
      branch: ${{ github.ref_name }}
      distPath: './packages/frontend/dist'
