name: Validate PR

on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: ./.github/actions/validate

      # We had cases where the PR typecheck was fine, but the build failed
      # Let's make sure we don't deploy something that doesn't build
      - uses: ./.github/actions/build-frontend
        with:
          with-sentry: false
          sentry-url: ${{ vars.SENTRY_URL }}
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-org: ${{ vars.SENTRY_ORG }}
          sentry-project: ${{ vars.SENTRY_PROJECT }}


  # We had cases where the PR typecheck was fine, but the build failed
  # Let's make sure we don't deploy something that doesn't build
  build-frontend:
    uses: ./.github/workflows/_build-frontend.yml
    secrets: inherit
    with:
      with-sentry: false

  deploy-cloudflare:
    needs: [validate-pr, build-frontend]
    uses: ./.github/workflows/_deploy-cloudflare-pages.yml
    secrets: inherit

  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' }}
    needs: validate-pr

    permissions:
      pull-requests: write
      contents: write

    steps:
      # https://gist.github.com/xt0rted/46475099dc0a70ba63e16e3177407872
      # https://github.com/dependabot/fetch-metadata/issues/111
      - name: Generate app token
        id: generate-app-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Authenticate gh cli with app token
        run: echo "${{ steps.generate-app-token.outputs.token }}" | gh auth login --with-token

      # From https://github.com/dependabot/fetch-metadata
      - name: Approve a PR if not already approved
        id: dependabot-approve
        run: |
          gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "$PR_URL"
          else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
